name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Install Trunk
      run: cargo install --locked trunk
    - name: Build the wasm
      run: trunk build --public-url ${{ github.event.repository.name }} --release
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: "./dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1